[project]
name = 'Education-and-Certification-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.assessment]
path = 'contracts/assessment.clar'
clarity_version = 2
epoch = 2.5

[contracts.certification-issuance]
path = 'contracts/certification-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.course-management]
path = 'contracts/course-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.skill-endorsement]
path = 'contracts/skill-endorsement.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
